# Generated by Django 5.2.5 on 2025-08-28 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
