# Generated by Django 5.2.5 on 2025-08-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0002_alter_performancereview_id'),
        ('user', '0008_alter_employee_company_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_approved', to='user.employee'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to='user.employee'),
        ),
    ]
