# Generated by Django 5.2.5 on 2025-08-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_performancereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
