# Generated by Django 5.2.5 on 2025-08-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_slug_alter_department_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceReview',
        ),
    ]
