# Generated by Django 5.2.5 on 2025-08-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_delete_performancereview'),
        ('user', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='user.employee'),
        ),
    ]
