# Generated by Django 5.2.5 on 2025-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_project_assigned_employees'),
        ('user', '0008_alter_employee_company_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_employees',
            field=models.ManyToManyField(related_name='projects', to='user.employee'),
        ),
    ]
