# Generated by Django 5.2.5 on 2025-08-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
